easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        User:
          class: App\Entity\User
        Demande:
          class: App\Entity\Demande
        Country:
          class: App\Entity\Country
        Appelle:
          class: App\Entity\Appelle
        Config:
          class: App\Entity\Config
        MicroPaiement:
          class: App\Entity\MicroPaiement
        Product:
          class: App\Entity\Product
          list:
            fields:
              - "id"
              - "filename"
              - "title"
              - "price"
              - { property: "image" , type : "image", base_path : "/images/"}
          form:
            fields:
              - "title"
              - "price"
              - { property: "file" , type : "vich_image"}

